development:
  cloud_name: defmethod
  api_key: '279358628796877'
  api_secret: vNgoaElPZ0wls8d1VTKIqyVA23Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: defmethod
  api_key: '279358628796877'
  api_secret: vNgoaElPZ0wls8d1VTKIqyVA23Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: defmethod
  api_key: '279358628796877'
  api_secret: vNgoaElPZ0wls8d1VTKIqyVA23Y
  enhance_image_tag: true
  static_image_support: false
